# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you don't want to use dynamic frameworks

target 'ZJPDouYuZB' do
 
  use_frameworks!

  # Pods for ZJPDouYuZB

pod 'Alamofire','~> 5.4.3'

end
